default:
    DataRoot: "<ABSOLUTE_PATH>/MetaBGC-TIIPKS/benchmark_data/TcmI"
    InputFiles.ProtAlnFasta: "TcmI.fasta"
    InputFiles.HMMRun: "Combined_spHMM_Search.txt"
    InputFiles.BLAST_IGNORE: ""
    InputFiles.BLAST_TP_NoCov: "All_TP_Blast.txt"
    InputFiles.GeneIntervalPos: "Gene_Interval_Pos.txt"
    InputFiles.GeneIntervalBlast: ""
    InputFiles.HMMUniqueBlast: ""
    InputFiles.HMM_Cutoff_Scores: "HMM_Score_Cutoff.txt" 
    InputFiles.ScaffoldCheck: "ScaffoldChecks.txt"
    InputParam.HMM_Model_Name: "TcmI"
    InputParam.Seq_start: 1
    InputParam.Seq_end: 114
    InputParam.F1_Threshold: 0.50
    OutputFiles.HMMOutDir: "output/spHMM"
    OutputFiles.HMMHighPerfOutDir: "output/spHMM/HighPerf"
    OutputFiles.SampleReadIdDir: "output/Sample_ReadIds"
    OutputFiles.F1_Cutoff: "output/TcmI_F1_Cutoff.txt"
    OutputFiles.Plot: "output/OxyN_synthetic_F1-final.eps"
    OutputFiles.ModelData: "output/TcmI-final_models-data.txt"
    OutputFiles.RawModelData: "output/TcmI-final_data-raw.txt"

